Iter13
AnatolySnegovskiy/metric pull request #13
Opened 2024-04-13 16:39 UTC by AnatolySnegovskiy

2024-04-17 05:34 UTC, arttet requested changes

2024-04-17 05:34 UTC, arttet commented on internal/repositories/counter.go
> +	_, err := c.pg.Exec("CREATE TABLE IF NOT EXISTS counter (name varchar(100) PRIMARY KEY, value int8)")
CHANGE REQUEST: please use migrations

2024-04-17 05:34 UTC, arttet commented on internal/repositories/counter.go
> +	_, err := c.pg.Exec("CREATE TABLE IF NOT EXISTS counter (name varchar(100) PRIMARY KEY, value int8)")
CLARIFICATION: are you sure that `name varchar(100) PRIMARY KEY` is good?

2024-04-17 05:34 UTC, arttet commented on internal/repositories/counter.go
> +func (c *CounterRepo) GetList() (pgx.Rows, error) {
CHANGE REQUEST: please avoid implementation details.

2024-04-17 16:44 UTC, AnatolySnegovskiy commented on internal/repositories/counter.go
> +	_, err := c.pg.Exec("CREATE TABLE IF NOT EXISTS counter (name varchar(100) PRIMARY KEY, value int8)")
а какая разница поставлю я 255 и так же мы будем не уверены в том что ключ будет меньше 255. 100 символов это достаточно большое количество, но ок поставлю 255 на миграции

2024-04-17 19:03 UTC, AnatolySnegovskiy commented on internal/repositories/counter.go
> +	_, err := c.pg.Exec("CREATE TABLE IF NOT EXISTS counter (name varchar(100) PRIMARY KEY, value int8)")
++

2024-04-17 19:12 UTC, AnatolySnegovskiy commented on internal/repositories/counter.go
> +func (c *CounterRepo) GetList() (pgx.Rows, error) {
++

2024-04-17 19:12 UTC, AnatolySnegovskiy commented on internal/repositories/counter.go
> +	_, err := c.pg.Exec("CREATE TABLE IF NOT EXISTS counter (name varchar(100) PRIMARY KEY, value int8)")
++

2024-04-21 12:01 UTC, arttet requested changes

2024-04-21 12:01 UTC, arttet commented on internal/entity/metrics/counter.go
> +		return c.rep.AddMetric(name, int(c.Items[name]))
CHANGE REQUEST: please use `context`

2024-04-21 12:01 UTC, arttet commented on internal/entity/metrics/counter.go
> +		return c.rep.AddMetrics(c.Items)
CHANGE REQUEST: please add `context`

2024-04-21 12:01 UTC, arttet commented on internal/entity/metrics/counter.go
> +func (c *Counter) GetList() (map[string]float64, error) {
CLARIFICATION: what should you add here?

2024-04-21 12:01 UTC, arttet commented on internal/entity/metrics/gauge.go
> +		return g.rep.AddMetric(name, g.Items[name])
CLARIFICATION: what do you need to use here?

2024-04-21 12:01 UTC, arttet commented on internal/entity/metrics/gauge.go
> +		return g.rep.AddMetrics(g.Items)
CLARIFICATION: what do you need to use here?

2024-04-21 12:01 UTC, arttet commented on internal/repositories/counter.go
> +func (c *CounterRepo) GetItem(name string) (int, error) {
CLARIFICATION: what do you need to use here?

2024-04-21 12:01 UTC, arttet commented on internal/repositories/counter.go
> +func (c *CounterRepo) GetList() (map[string]float64, error) {
CLARIFICATION: what do you need to use here?

2024-04-21 12:01 UTC, arttet commented on internal/repositories/counter.go
> +	query := fmt.Sprintf("INSERT INTO counter (name, value) VALUES %s ON CONFLICT (name) DO UPDATE SET value = EXCLUDED.value", strings.Join(valueStrings, ","))
CLARIFICATION: what if the length of the array above 1024?

2024-04-21 12:01 UTC, arttet commented on internal/storages/clients/postgres.go
> +	ctx  context.Context
CHANGE REQUEST: it should be a parameter of the function

2024-04-21 12:01 UTC, arttet commented on internal/storages/migrations/001_init.sql
> +CREATE TABLE IF NOT EXISTS counter (name varchar(255) PRIMARY KEY, value int8);
```suggestion
CREATE TABLE counter (name varchar(255) PRIMARY KEY, value int8);
```

2024-04-21 12:01 UTC, arttet commented on internal/storages/migrations/001_init.sql
> +CREATE TABLE IF NOT EXISTS gauge (name varchar(255) PRIMARY KEY, value DOUBLE PRECISION);
```suggestion
CREATE TABLE gauge (name varchar(255) PRIMARY KEY, value DOUBLE PRECISION);
```

2024-04-21 12:01 UTC, arttet commented on tern.conf
> +[database]
CLARIFICATION: what is it?

2024-04-21 12:01 UTC, arttet commented on internal/repositories/counter.go
> +	_, err := c.pg.Exec("CREATE TABLE IF NOT EXISTS counter (name varchar(100) PRIMARY KEY, value int8)")
Why not `id INT GENERATED ALWAYS AS IDENTITY,` ?

2024-04-21 12:04 UTC, AnatolySnegovskiy commented on tern.conf
> +[database]
это конфиг библы миграций

2024-04-21 12:08 UTC, AnatolySnegovskiy commented on internal/storages/migrations/001_init.sql
> +CREATE TABLE IF NOT EXISTS gauge (name varchar(255) PRIMARY KEY, value DOUBLE PRECISION);
++

2024-04-21 12:08 UTC, AnatolySnegovskiy commented on internal/storages/migrations/001_init.sql
> +CREATE TABLE IF NOT EXISTS counter (name varchar(255) PRIMARY KEY, value int8);
++

2024-04-21 12:09 UTC, AnatolySnegovskiy commented on internal/storages/clients/postgres.go
> +	ctx  context.Context
Зачем в каждой функции передвать контекст, если мы можем сразу задать контекст структуре и использовать его внутри структуры, зачем плодить аргументы безсмысленные?

2024-04-21 12:10 UTC, AnatolySnegovskiy commented on internal/entity/metrics/gauge.go
> +		return g.rep.AddMetrics(g.Items)
Если ознакомиться со спритом то станет понятно что нужно поддержать работы и без базы

2024-04-21 12:10 UTC, AnatolySnegovskiy commented on internal/entity/metrics/gauge.go
> +		return g.rep.AddMetric(name, g.Items[name])
Если ознакомиться со спритом то станет понятно что нужно поддержать работы и без базы

2024-04-21 12:11 UTC, AnatolySnegovskiy commented on internal/entity/metrics/counter.go
> +		return c.rep.AddMetric(name, int(c.Items[name]))
Зачем добавлять контекст если контекст задан не посредственно в структуре репозитория

2024-04-21 12:11 UTC, AnatolySnegovskiy commented on internal/entity/metrics/counter.go
> +		return c.rep.AddMetrics(c.Items)
Зачем добавлять контекст если контекст задан не посредственно в структуре репозитория

2024-04-21 12:11 UTC, AnatolySnegovskiy commented on internal/entity/metrics/counter.go
> +func (c *Counter) GetList() (map[string]float64, error) {
Зачем добавлять контекст если контекст задан не посредственно в структуре репозитория

2024-04-21 13:54 UTC, AnatolySnegovskiy commented on internal/storages/clients/postgres.go
> +	ctx  context.Context
++

2024-04-21 13:54 UTC, AnatolySnegovskiy commented on internal/entity/metrics/gauge.go
> +		return g.rep.AddMetrics(g.Items)
++

2024-04-21 13:54 UTC, AnatolySnegovskiy commented on internal/entity/metrics/gauge.go
> +		return g.rep.AddMetric(name, g.Items[name])
++

2024-04-21 13:55 UTC, AnatolySnegovskiy commented on internal/entity/metrics/counter.go
> +func (c *Counter) GetList() (map[string]float64, error) {
++

2024-04-21 13:55 UTC, AnatolySnegovskiy commented on internal/entity/metrics/counter.go
> +		return c.rep.AddMetrics(c.Items)
++

2024-04-21 13:55 UTC, AnatolySnegovskiy commented on internal/entity/metrics/counter.go
> +		return c.rep.AddMetric(name, int(c.Items[name]))
++

2024-04-21 15:19 UTC, arttet approved these changes

2024-04-21 15:19 UTC, arttet commented on cmd/server/main.go
> +		migration, _ := migrate.NewMigrator(context.Background(), db, "public.schema_version")
SUGGESTION: you can create a context once.

2024-04-21 15:19 UTC, arttet commented on internal/entity/metrics/counter.go
> +func NewCounter(rep *repositories.CounterRepo) *Counter {
```suggestion
func NewCounter(repo *repositories.CounterRepo) *Counter {
```

2024-04-21 15:19 UTC, arttet commented on internal/repositories/counter.go
> +	rows, err := c.pg.Query(ctx, "SELECT * FROM counter")
CLARIFICATION: what if you change a db scheme?

2024-04-21 15:19 UTC, arttet commented on internal/services/agent/run.go
> +				if retrievableCounter < a.maxRetries {
https://github.com/cenkalti/backoff

2024-04-21 15:19 UTC, arttet commented on internal/services/agent/update.go
> +		if gauge.Process(context.Background(), field, fmt.Sprintf("%v", reflect.ValueOf(m).FieldByName(field))) != nil {
SUGGESTION: it would be better if you use a timeout here.

2024-04-21 15:19 UTC, arttet commented on internal/storages/clients/postgres.go
> +type PgxIface interface {
SUGGESTION: If I were you, I would avoid it

2024-04-22 06:33 UTC, merged

2024-04-22 06:38 UTC, AnatolySnegovskiy commented on internal/storages/clients/postgres.go
> +type PgxIface interface {
это нужно для создания моков